/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2026-04-21 10:34:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Beauty Salon</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #f4f4f4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            bottom:35em;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            color: darkmagenta;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 0.5em;\r\n");
      out.write("            z-index: 2; /* Ensure the header is above the carousel */\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between; /* Align items horizontally */\r\n");
      out.write("            align-items: center; /* Align items vertically */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav {\r\n");
      out.write("            padding: 1em;\r\n");
      out.write("            text-align: right; /* Align navigation items to the right */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav a {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 0.2em 0.5em;\r\n");
      out.write("            margin: 0.1em;\r\n");
      out.write("            border-radius: 10px 1px;\r\n");
      out.write("            background-color: #444; /* Background color only till text */\r\n");
      out.write("            display: inline-block; /* Display as inline-block to apply background only to the text */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1; /* Ensure the carousel is behind the header and navigation */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-inner {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-item {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-item video {\r\n");
      out.write("            width: %;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-caption {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translate(-50%, -50%);\r\n");
      out.write("        z-index: 3; /* Set a z-index higher than the carousel items */\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #fff; /* Adjust text color as needed */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        section {\r\n");
      out.write("            padding: 2em;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size:4em; /* Font size */\r\n");
      out.write("            font-family: \"Times New Roman\", Times, serif; /* Change font family */\r\n");
      out.write("            font-style: italic; /* Change font style */\r\n");
      out.write("        	text-shadow: 2px 1px pink;\r\n");
      out.write("        }\r\n");
      out.write("        .line-break {\r\n");
      out.write("            display: block; /* Display as block to force line break */\r\n");
      out.write("            margin-right: 5em; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 0.5em 1em;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #555;\r\n");
      out.write("        }\r\n");
      out.write("        /* Modal CSS */\r\n");
      out.write(".modal {\r\n");
      out.write("  display: none; /* Hidden by default */\r\n");
      out.write("  position: fixed; /* Stay in place */\r\n");
      out.write("  z-index: 9999; /* Sit on top */\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 100%; /* Full width */\r\n");
      out.write("  height: 100%; /* Full height */\r\n");
      out.write("  overflow: auto; /* Enable scroll if needed */\r\n");
      out.write("  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content */\r\n");
      out.write(".modal-content {\r\n");
      out.write("  background-color: #fefefe;\r\n");
      out.write("  margin: 15% auto; /* 15% from the top and centered */\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  border: 1px solid #888;\r\n");
      out.write("  width: 80%; /* Could be more or less, depending on screen size */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Close Button */\r\n");
      out.write(".close {\r\n");
      out.write("  color: #aaa;\r\n");
      out.write("  float: right;\r\n");
      out.write("  font-size: 28px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover,\r\n");
      out.write(".close:focus {\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1> Classy <span class=\"line-break\"></span>  Salon </h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"Services.jsp\">Services</a>\r\n");
      out.write("            <a href=\"Contact.jsp\">Contact</a>\r\n");
      out.write("            <a href=\"Registration.jsp\">Login/Signup</a>\r\n");
      out.write("            <a href=\"#aboutus\" id=\"aboutUsLink\"> About us </a>\r\n");
      out.write("            <a href=\"Appointment.jsp\"> Appointment </a>\r\n");
      out.write("            <a href=\"Alogin.jsp\"> Staff </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"carousel-container-fluid\">\r\n");
      out.write("        <div id=\"carouselExampleControls\" class=\"carousel slide vertical\" data-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <!-- First slide -->\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <video autoplay muted loop width=\"100%\" height=\"auto\">\r\n");
      out.write("                        <source src=\"images/bs1.mp4\" type=\"video/mp4\">\r\n");
      out.write("					</video>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Modal HTML -->\r\n");
      out.write("<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <span class=\"close\">&times;</span>\r\n");
      out.write("    <p id=\"modal-text\"></p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("     <script>\r\n");
      out.write("        // Add an event listener to the \"Appointment\" navigation link\r\n");
      out.write("        document.querySelector('a[href=\"Appointment.jsp\"]').addEventListener('click', function(event) {\r\n");
      out.write("            // Display a popup box\r\n");
      out.write("            alert('You have to login to your account to .');\r\n");
      out.write("            // Prevent the default action of following the link\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write(" // Add an event listener to the \"About us\" navigation link\r\n");
      out.write("    document.getElementById('aboutUsLink').addEventListener('click', function(event) {\r\n");
      out.write("        event.preventDefault(); // Prevent the default behavior of following the link\r\n");
      out.write("        document.getElementById('modal-text').innerText = 'V.S Salon, dedicated to enhancing your natural beauty and boosting your confidence. With years of experience in the beauty industry, our talented team of stylists and professionals are committed to providing top-notch services tailored to your needs. Step into our welcoming space, where relaxation and transformation await. Let us pamper you with our expertise and personalized care. Discover the ultimate salon experience with us today!'; // Set the text content of the modal\r\n");
      out.write("        document.getElementById('myModal').style.display = 'block'; // Display the modal\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Get the close button element\r\n");
      out.write("    var closeButton = document.getElementsByClassName(\"close\")[0];\r\n");
      out.write("\r\n");
      out.write("    // When the user clicks on the close button, close the modal\r\n");
      out.write("    closeButton.onclick = function() {\r\n");
      out.write("      document.getElementById('myModal').style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("    window.onclick = function(event) {\r\n");
      out.write("      if (event.target == document.getElementById('myModal')) {\r\n");
      out.write("        document.getElementById('myModal').style.display = 'none';\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
