/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2026-04-21 11:10:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Beauty Salon</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {  \r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background-color: #9a90f5;\r\n");
      out.write("            background-image: url(images/background.jpg);\r\n");
      out.write("            background-size: 100%;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            color: darkmagenta;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 0.5em;\r\n");
      out.write("            z-index: 2; /* Ensure the header is above the carousel */\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between; /* Align items horizontally */\r\n");
      out.write("            align-items: center; /* Align items vertically */\r\n");
      out.write("        }\r\n");
      out.write("        nav {\r\n");
      out.write("            padding: 1em;\r\n");
      out.write("            text-align: right; /* Align navigation items to the right */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        nav a {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 0.2em 0.5em;\r\n");
      out.write("            margin: 0.1em;\r\n");
      out.write("            border-radius: 10px 1px;\r\n");
      out.write("            background-color: #444; /* Background color only till text */\r\n");
      out.write("            display: inline-block; /* Display as inline-block to apply background only to the text */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav a:hover {\r\n");
      out.write("                background-color: aliceblue;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-menu-up {\r\n");
      out.write("            top: auto;\r\n");
      out.write("            bottom: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        section {\r\n");
      out.write("            padding: 2em;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size:4em; /* Font size */\r\n");
      out.write("            font-family: \"Times New Roman\", Times, serif; /* Change font family */\r\n");
      out.write("            font-style: italic; /* Change font style */\r\n");
      out.write("            text-shadow: 2px 1px pink;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-menu-up {\r\n");
      out.write("            top: auto;\r\n");
      out.write("            bottom: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        section {\r\n");
      out.write("            padding: 2em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: ghostwhite;\r\n");
      out.write("            text-align: center; /* Center align the text */\r\n");
      out.write("            margin: 2em auto; /* Center the element horizontally and add some margin */\r\n");
      out.write("            max-width: 400px; /* Limit the width of the element */\r\n");
      out.write("            padding: 0.5em; /* Add padding */\r\n");
      out.write("            background-color: #333; /* Background color for the <h2> */\r\n");
      out.write("            border-radius: 2px 40px; /* Optional border-radius for rounded corners */\r\n");
      out.write("            display: block; /* Set to inline-block to only cover the width of the text */\r\n");
      out.write("            box-shadow: 1px 4px whitesmoke;\r\n");
      out.write("        }\r\n");
      out.write("        .line-break {\r\n");
      out.write("            display: block; /* Display as block to force line break */\r\n");
      out.write("            margin-right: 5em; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .services {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service {\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding: 1em;\r\n");
      out.write("            margin: 1em;\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        form { \r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("            margin: 2em auto;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            padding: 1em;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            box-shadow: 0px 0px 10px 2px rgba(0,0,0,0.9);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input,\r\n");
      out.write("        textarea,\r\n");
      out.write("        button {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-bottom: 1em;\r\n");
      out.write("            padding: 0.5em;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: ghostwhite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 0.5em 1em;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #555;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-menu {\r\n");
      out.write("            background-color: #444;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>Classy<span class=\"line-break\"></span>Salon </h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"#services\">Services</a>\r\n");
      out.write("            <a href=\"Contact.jsp\">Need Help</a>\r\n");
      out.write("            <a href=\"Home.jsp\"> Home </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <h2 class=\"mb-4\">Sign Up</h2>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"reg\" method=\"post\" onsubmit=\"return validatePassword()\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"firstName\">First Name:</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\" oninput=\"this.value = this.value.replace(/[^a-zA-Z]/g, '')\" required>\r\n");
      out.write("        <br>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"lastName\">Last Name:</label>\r\n");
      out.write("            <input type=\"text\"  class=\"form-control\" id=\"lastName\" name=\"lastName\" oninput=\"this.value = this.value.replace(/[^a-zA-Z]/g, '')\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"phonenumber\"> Phone Number: </label>\r\n");
      out.write("           <input type=\"text\" class=\"form-control\" id=\"phoneNumber\" name=\"phoneNumber\" maxlength=\"10\" oninput=\"this.value = this.value.replace(/[^0-9]/g, '')\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"email\">Email:</label>\r\n");
      out.write("            <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"password\">Password:</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">Register</button>\r\n");
      out.write("        <div class=\"Click here\">\r\n");
      out.write("        <p>have an account? <a href=\"Login.jsp\">Click here</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    function validatePassword() {\r\n");
      out.write("        var password = document.getElementById(\"password\").value;\r\n");
      out.write("        \r\n");
      out.write("        if (password.length < 8 || !/[A-Z]/.test(password) || !/\\d/.test(password)) {\r\n");
      out.write("            alert(\"Password must be at least 8 characters long and contain at least one uppercase letter and one number.\");\r\n");
      out.write("            return false; // Prevent form submission\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
